version: '3.7'

services:
  web:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine
    volumes:
      - tlp_postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db.prod

  tg:
    build: ./telegram
    command: python main.py
    ports:
      - '80:80'
    env_file:
      - telegram/.env.tg
    depends_on:
      - db
      - web


volumes:
  tlp_postgres_data:

