version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine
    volumes:
      - tlp_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.prod

  nginx:
    build: ./nginx
    ports:
      - '80:80'
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    depends_on:
      - web

  telegram:
    build: ./telegram
    volumes:
      - tg_data:/usr/src/app/telegram
    command: python main.py
    env_file:
      - ./telegram/.env.tg
    ports:
      - '88:88'

    depends_on:
      - nginx



volumes:
  tlp_postgres_data:
  static_volume:
  media_volume:
  tg_data: