version: '3.7'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    volumes:
      - tlp_postgres_data:/var/lib/postgresql/data/

volumes:
  tlp_postgres_data: