version: '3.7'

services:
  web:
    build: ./
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine
    volumes:
      - tlp_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.prod
volumes:
  tlp_postgres_data:

