version: '3.7'

services:
  django:
    container_name: tlp
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python /usr/src/tlp/manage.py migrate --noinput &&
                      python /usr/src/tlp/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/tlp
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:

